### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by lucasromanojf** [sencha/extjs-reactor#243] opened 2017-06-17 16:49 UTC
Hi,

I'm trying to deploy a ExtReact app on Linux but, when I run "npm run build", the following error happens:

`
94% asset optimization
building ExtReact bundle: ext => /app/build/ext-react
module.js:319
  var reqLen = request.length;
                      ^

TypeError: Cannot read property 'length' of undefined
    at Function.Module._resolveLookupPaths (module.js:319:23)
    at Function.Module._resolveFilename (module.js:460:31)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/app/node_modules/@extjs/reactor-webpack-plugin/node_modules/@extjs/sencha-cmd/bin/sencha:14:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
`

Then the ext.js file is not created and app does not work.

Please, can you help me?

Thanks!

**Comment by markbrocato** [comment] 2017-06-18 22:02
@israelroldan We've seen that a few times before.  Do you know what's the cause?

**Comment by israelroldan** [comment] 2017-06-21 11:25
@lucasromanojf This issue has been fixed in `@extjs/sencha-cmd@next`.

If you're running this in monorepo mode (meaning that you ran "npm install" at the root for `extjs-reactor`, you'll need to run `npm install @extjs/sencha-cmd@next` from within the `packages/reactor-webpack-plugin` directory.

Otherwise, if you're running on a "standalone" project (where packages came directly from an npm registry: ours or npm's), then you'll need to run that command from inside the `node_modules/@extjs/reactor-webpack-plugin` directory.

**Comment by markbrocato** [comment] 2017-07-27 14:11
This should be fixed with the latest release of reactor-webpack-plugin@1.1.0.  Feel free to reopen if you still run into this error on the latest version.

**Closed by markbrocato** 2017-07-27 14:11 UTC
