### ISSUE TITLE
modern-boilerplate 1.0.0 : npm start fails

### ISSUE THREAD

**Issue by abenhamdine** [sencha/extjs-reactor#203] opened 2017-05-16 14:10 UTC
## Expected Behavior
npm start succeed and http://localhost:8086/ runs normally.

## Current Behavior
```bash
Arnaud Benhamdine@LAPTOP-ARNAUD MINGW64 /c/node-projects/extjs-reactor/packages/reactor-modern-boilerplate
$ npm start

> @extjs/react-modern-boilerplate@1.0.0 start C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate
> webpack-dev-server --progress --colors

 10% building modules 1/1 modules 0 active
Project is running at http://localhost:8086/
webpack output is served from /
Content not from webpack is served from ./build
404s will fallback to /index.html                                                                                      94% asset optimization                   building ExtReact bundle: ext => C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\build\ext-react
Sencha Cmd v6.5.0.180
[INF] Loading compiler context
[ERR] Cannot satisfy requirements for "modern"!
[ERR]    The following versions cannot be satisfied:
[ERR]       null: modern (No matches!)
[ERR]
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExVersion: Cannot resolve package requirements
[ERR]
[ERR] Total time: 3 seconds
[ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExVersion: Cannot resolve package requirements
undefined
(node:9108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of undefined
(node:9108) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
webpack: wait until bundle finished: /
```
## Steps to Reproduce (for bugs)
```
cd C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate
mklink ext c:\sencha-sdks\ext-6.5.0
npm install
npm start
```

## Your Environment
Sencha Cmd v6.5.0.180
WIndows 10
Ext 6.5.0
react-modern-boilerplate@1.0.0 
npm 4.2.0

**Comment by markbrocato** [comment] 2017-05-16 14:23
Weird, I just tried the same workflow on Mac OS and it's working fine.  Would you mind copying the sdk to the ext folder instead of linking it?  I'm not sure how much I trust links on windows :).

**Comment by mpidev** [comment] 2017-05-16 14:48
reactor-modern-boilerplate ->  is working just fine (Mac OS)
![2017-05-16_10-47-41](https://cloud.githubusercontent.com/assets/3986928/26112188/3382895a-3a25-11e7-9600-e4de36ec9e1e.png)

**Comment by mpidev** [comment] 2017-05-16 14:54
If you do not have link to ext (sencha) lib or link goes to the wrong place 
after >  npm start
you will have that error: 

```
[INF] Loading compiler context
[ERR] Cannot satisfy requirements for "modern"!
[ERR]    The following versions cannot be satisfied:
[ERR]       null: modern (No matches!)
```

**Comment by abenhamdine** [comment] 2017-05-16 15:23
Hmm I had the same error, after copying the sdk folder at the root of the boilerplate.
I don't see what I'm missing.

**Comment by markbrocato** [comment] 2017-05-16 15:34
Maybe just try downloading a fresh copy of the SDK from the support portal?  Failing that, can you post a screenshot of your project tree?

**Comment by mpidev** [comment] 2017-05-16 17:48
No more {install} ?
Is it right to replace ?
```
import { install } from '@extjs/reactor';
install();
```
... to...
```
import { launch } from '@extjs/reactor';
const MOUNT_NODE = document.getElementById('root')
launch(<AppContainer store={store} routes={routes} />, MOUNT_NODE);
```

**Comment by markbrocato** [comment] 2017-05-16 18:06
See http://docs.sencha.com/extreact/6.5.0/guides/getting_started.html#getting_started_-_launching_your_application

Yes, `install` is deprecated.  For if you're using an ExtReact `Container` as your root layout component, you don't need a target div, simply do:

```jsx
import { launch } from '@extjs/reactor';
launch(<AppContainer store={store} routes={routes} />);
```

If you're using an ExtReact `Container` within the context of a larger app, you can do:

```jsx
launch(() => {
  ReactDOM.render(<App/>, MOUNT_TARGET)
})
```

**Comment by tskipa** [comment] 2017-05-17 06:57
I have exact same problem with classic boilerplate on windows 10.
`Sencha Cmd v6.5.0.180

[INF] Loading compiler context
[ERR] Cannot satisfy requirements for "classic"!

[ERR]    The following versions cannot be satisfied:

[ERR]       null: classic (No matches!)`

**Comment by abenhamdine** [comment] 2017-05-17 10:06
It didn't solve the pb for me, I still have the same error, even after edited packages.json : 

```bash
$ npm run build

> @extjs/react-modern-boilerplate@1.0.0 build C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate
> npm run clean && SET NODE_ENV=production & webpack --env.prod=true --progress --colors


> @extjs/react-modern-boilerplate@1.0.0 clean C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate
> rimraf build

 94% asset optimization
building ExtReact bundle: ext => C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\build\ext-react
'C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\@extjs\sencha-cmd\bin\sencha' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.
{ Error: Command failed: C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\@extjs\sencha-cmd\bin\sencha ant build
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\@extjs\reactor-webpack-plugin\dist\index.js:414:49
    at ReactExtJSWebpackPlugin._buildExtBundle (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\@extjs\reactor-webpack-plugin\dist\index.js:329:20)
    at Compiler.<anonymous> (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\@extjs\reactor-webpack-plugin\dist\index.js:205:23)
    at Compiler.applyPluginsAsyncSeries (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:142:13)
    at Compiler.emitAssets (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\Compiler.js:308:7)
    at onCompiled (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\Compiler.js:247:11)
    at C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\Compiler.js:499:13
    at next (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:138:11)
    at Compiler.<anonymous> (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:142:13)
    at C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\Compiler.js:496:10
    at Compilation.applyPluginsAsyncSeries (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:131:46)
    at self.applyPluginsAsync.err (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\Compilation.js:649:19)
    at next (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.compilation.plugin (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\ProgressPlugin.js:121:6)
    at Compilation.applyPluginsAsyncSeries (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:142:13)
    at self.applyPluginsAsync.err (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\Compilation.js:640:11)
    at next (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.compilation.plugin (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\ProgressPlugin.js:117:6)
    at next (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:140:14)
    at Compilation.compilation.plugin (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\optimize\UglifyJsPlugin.js:230:5)
    at Compilation.applyPluginsAsyncSeries (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:142:13)
    at self.applyPluginsAsync.err (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\Compilation.js:635:10)
    at next (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.compilation.plugin.callback (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\ProgressPlugin.js:113:6)
    at Compilation.applyPluginsAsyncSeries (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:142:13)
    at sealPart2 (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\webpack\lib\Compilation.js:631:9)
    at next (C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\tapable\lib\Tapable.js:138:11)
  error: null,
  cmd: 'C:\\node-projects\\extjs-reactor\\packages\\reactor-modern-boilerplate\\node_modules\\@extjs\\sencha-cmd\\bin\\sencha ant build',
  file: 'C:\\WINDOWS\\system32\\cmd.exe',
  args:
   [ 'C:\\WINDOWS\\system32\\cmd.exe',
     '/d',
     '/s',
     '/c',
     '"C:\\node-projects\\extjs-reactor\\packages\\reactor-modern-boilerplate\\node_modules\\@extjs\\sencha-cmd\\bin\\sencha ant build"' ],
  options:
   { cwd: 'C:\\node-projects\\extjs-reactor\\packages\\reactor-modern-boilerplate\\build\\ext-react',
     stdio: [ [Object], [Object], [Object] ],
     shell: true,
     windowsVerbatimArguments: true,
     file: 'C:\\WINDOWS\\system32\\cmd.exe',
     args:
      [ 'C:\\WINDOWS\\system32\\cmd.exe',
        '/d',
        '/s',
        '/c',
        '"C:\\node-projects\\extjs-reactor\\packages\\reactor-modern-boilerplate\\node_modules\\@extjs\\sencha-cmd\\bin\\sencha ant build"' ],
     envPairs:
      [ 'ACLOCAL_PATH=C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal',
        'ALLUSERSPROFILE=C:\\ProgramData',
        'APPDATA=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming',
        'COMMONPROGRAMFILES=C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
        'CommonProgramW6432=C:\\Program Files\\Common Files',
        'COMPUTERNAME=LAPTOP-ARNAUD',
        'COMSPEC=C:\\WINDOWS\\system32\\cmd.exe',
        'CONFIG_SITE=C:/Program Files/Git/mingw64/etc/config.site',
        'CYGWIN=mintty',
        'DISPLAY=needs-to-be-defined',
        'EXEPATH=C:\\Program Files\\Git',
        'GYP_MSVS_VERSION=2015',
        'HOME=C:\\Users\\Arnaud Benhamdine',
        'HOMEDRIVE=C:',
        'HOMEPATH=\\Users\\Arnaud Benhamdine',
        'HOSTNAME=LAPTOP-ARNAUD',
        'INFOPATH=C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info',
        'LANG=fr_FR.UTF-8',
        'LOCALAPPDATA=C:\\Users\\Arnaud Benhamdine\\AppData\\Local',
        'LOGONSERVER=\\\\LAPTOP-ARNAUD',
        'MANPATH=C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man',
        'MINGW_CHOST=x86_64-w64-mingw32',
        'MINGW_PACKAGE_PREFIX=mingw-w64-x86_64',
        'MINGW_PREFIX=C:/Program Files/Git/mingw64',
        'MSYSTEM=MINGW64',
        'MSYSTEM_CARCH=x86_64',
        'MSYSTEM_CHOST=x86_64-w64-mingw32',
        'MSYSTEM_PREFIX=C:/Program Files/Git/mingw64',
        'NODE=C:\\Program Files\\nodejs\\node.exe',
        'NODE_ENV=production ',
        'npm_config_access=',
        'npm_config_also=',
        'npm_config_always_auth=',
        'npm_config_argv={"remain":[],"cooked":["run","build"],"original":["run","build"]}',
        'npm_config_bin_links=true',
        'npm_config_browser=',
        'npm_config_ca=',
        'npm_config_cache=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming\\npm-cache',
        'npm_config_cache_lock_retries=10',
        'npm_config_cache_lock_stale=60000',
        'npm_config_cache_lock_wait=10000',
        'npm_config_cache_max=Infinity',
        'npm_config_cache_min=10',
        'npm_config_cafile=',
        'npm_config_cert=',
        'npm_config_color=true',
        'npm_config_depth=Infinity',
        'npm_config_description=true',
        'npm_config_dev=',
        'npm_config_dry_run=',
        'npm_config_editor=notepad.exe',
        'npm_config_engine_strict=',
        'npm_config_fetch_retries=2',
        'npm_config_fetch_retry_factor=10',
        'npm_config_fetch_retry_maxtimeout=60000',
        'npm_config_fetch_retry_mintimeout=10000',
        'npm_config_force=',
        'npm_config_git=git',
        'npm_config_git_tag_version=true',
        'npm_config_global=',
        'npm_config_globalconfig=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming\\npm\\etc\\npmrc',
        'npm_config_globalignorefile=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming\\npm\\etc\\npmignore',
        'npm_config_global_style=',
        'npm_config_group=',
        'npm_config_heading=npm',
        'npm_config_https_proxy=',
        'npm_config_if_present=',
        'npm_config_ignore_scripts=',
        'npm_config_init_author_email=',
        'npm_config_init_author_name=',
        'npm_config_init_author_url=',
        'npm_config_init_license=ISC',
        'npm_config_init_module=C:\\Users\\Arnaud Benhamdine\\.npm-init.js',
        'npm_config_init_version=1.0.0',
        'npm_config_json=',
        'npm_config_key=',
        'npm_config_legacy_bundling=',
        'npm_config_link=',
        'npm_config_local_address=',
        'npm_config_loglevel=warn',
        'npm_config_logs_max=10',
        'npm_config_long=',
        'npm_config_maxsockets=50',
        'npm_config_message=%s',
        'npm_config_metrics_registry=https://registry.npmjs.org/',
        'npm_config_msvs_version=2015',
        'npm_config_node_version=7.10.0',
        'npm_config_onload_script=',
        'npm_config_only=',
        'npm_config_optional=true',
        'npm_config_parseable=',
        'npm_config_prefix=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming\\npm',
        'npm_config_production=',
        'npm_config_progress=true',
        'npm_config_proprietary_attribs=true',
        'npm_config_proxy=',
        'npm_config_python=C:\\Users\\Arnaud Benhamdine\\.windows-build-tools\\python27\\python.exe',
        'npm_config_rebuild_bundle=true',
        'npm_config_registry=https://registry.npmjs.org/',
        ... 110 more items ] },
  envPairs:
   [ 'ACLOCAL_PATH=C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal',
     'ALLUSERSPROFILE=C:\\ProgramData',
     'APPDATA=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming',
     'COMMONPROGRAMFILES=C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
     'CommonProgramW6432=C:\\Program Files\\Common Files',
     'COMPUTERNAME=LAPTOP-ARNAUD',
     'COMSPEC=C:\\WINDOWS\\system32\\cmd.exe',
     'CONFIG_SITE=C:/Program Files/Git/mingw64/etc/config.site',
     'CYGWIN=mintty',
     'DISPLAY=needs-to-be-defined',
     'EXEPATH=C:\\Program Files\\Git',
     'GYP_MSVS_VERSION=2015',
     'HOME=C:\\Users\\Arnaud Benhamdine',
     'HOMEDRIVE=C:',
     'HOMEPATH=\\Users\\Arnaud Benhamdine',
     'HOSTNAME=LAPTOP-ARNAUD',
     'INFOPATH=C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info',
     'LANG=fr_FR.UTF-8',
     'LOCALAPPDATA=C:\\Users\\Arnaud Benhamdine\\AppData\\Local',
     'LOGONSERVER=\\\\LAPTOP-ARNAUD',
     'MANPATH=C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man',
     'MINGW_CHOST=x86_64-w64-mingw32',
     'MINGW_PACKAGE_PREFIX=mingw-w64-x86_64',
     'MINGW_PREFIX=C:/Program Files/Git/mingw64',
     'MSYSTEM=MINGW64',
     'MSYSTEM_CARCH=x86_64',
     'MSYSTEM_CHOST=x86_64-w64-mingw32',
     'MSYSTEM_PREFIX=C:/Program Files/Git/mingw64',
     'NODE=C:\\Program Files\\nodejs\\node.exe',
     'NODE_ENV=production ',
     'npm_config_access=',
     'npm_config_also=',
     'npm_config_always_auth=',
     'npm_config_argv={"remain":[],"cooked":["run","build"],"original":["run","build"]}',
     'npm_config_bin_links=true',
     'npm_config_browser=',
     'npm_config_ca=',
     'npm_config_cache=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming\\npm-cache',
     'npm_config_cache_lock_retries=10',
     'npm_config_cache_lock_stale=60000',
     'npm_config_cache_lock_wait=10000',
     'npm_config_cache_max=Infinity',
     'npm_config_cache_min=10',
     'npm_config_cafile=',
     'npm_config_cert=',
     'npm_config_color=true',
     'npm_config_depth=Infinity',
     'npm_config_description=true',
     'npm_config_dev=',
     'npm_config_dry_run=',
     'npm_config_editor=notepad.exe',
     'npm_config_engine_strict=',
     'npm_config_fetch_retries=2',
     'npm_config_fetch_retry_factor=10',
     'npm_config_fetch_retry_maxtimeout=60000',
     'npm_config_fetch_retry_mintimeout=10000',
     'npm_config_force=',
     'npm_config_git=git',
     'npm_config_git_tag_version=true',
     'npm_config_global=',
     'npm_config_globalconfig=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming\\npm\\etc\\npmrc',
     'npm_config_globalignorefile=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming\\npm\\etc\\npmignore',
     'npm_config_global_style=',
     'npm_config_group=',
     'npm_config_heading=npm',
     'npm_config_https_proxy=',
     'npm_config_if_present=',
     'npm_config_ignore_scripts=',
     'npm_config_init_author_email=',
     'npm_config_init_author_name=',
     'npm_config_init_author_url=',
     'npm_config_init_license=ISC',
     'npm_config_init_module=C:\\Users\\Arnaud Benhamdine\\.npm-init.js',
     'npm_config_init_version=1.0.0',
     'npm_config_json=',
     'npm_config_key=',
     'npm_config_legacy_bundling=',
     'npm_config_link=',
     'npm_config_local_address=',
     'npm_config_loglevel=warn',
     'npm_config_logs_max=10',
     'npm_config_long=',
     'npm_config_maxsockets=50',
     'npm_config_message=%s',
     'npm_config_metrics_registry=https://registry.npmjs.org/',
     'npm_config_msvs_version=2015',
     'npm_config_node_version=7.10.0',
     'npm_config_onload_script=',
     'npm_config_only=',
     'npm_config_optional=true',
     'npm_config_parseable=',
     'npm_config_prefix=C:\\Users\\Arnaud Benhamdine\\AppData\\Roaming\\npm',
     'npm_config_production=',
     'npm_config_progress=true',
     'npm_config_proprietary_attribs=true',
     'npm_config_proxy=',
     'npm_config_python=C:\\Users\\Arnaud Benhamdine\\.windows-build-tools\\python27\\python.exe',
     'npm_config_rebuild_bundle=true',
     'npm_config_registry=https://registry.npmjs.org/',
     ... 110 more items ],
  stderr: null,
  stdout: null,
  pid: 3844,
  output: [ null, null, null ],
  signal: null,
  status: 1 }
```

**Comment by tskipa** [comment] 2017-05-17 10:09
Well, there is an additional problem of npm package: 
```
node_modules\@extjs\sencha-cmd\bin\sencha' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.

**Comment by markbrocato** [comment] 2017-05-17 12:58
The webpack plugin uses a node-wrapped version of sencha cmd. It looks like cmd is having trouble running.  I'm going to reach out to the Cmd team and see what they think.  In the meantime, do you have a JRE installed?

**Comment by markbrocato** [comment] 2017-05-17 13:25
I'm able to reproduce this on my Windows 10 VM.  Working on a fix...

**Comment by abenhamdine** [comment] 2017-05-17 14:44
FWIW, I have JRE 1.8.0 installed, but jre/bin is not in the PATH.

**Comment by israelroldan** [comment] 2017-05-17 16:57
@abenhamdine do you see a `sencha-cmd` directory in `C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\node_modules\@extjs\` if not, could you try installing it locally in the `reactor-modern-boilerplate` directory? 

    npm install @extjs/sencha-cmd

**Comment by abenhamdine** [comment] 2017-05-17 17:08
yes, the sencha-cmd folder is there :   

![image](https://cloud.githubusercontent.com/assets/7466144/26166364/8f004218-3b33-11e7-82c4-f4d93eced864.png)

I tried `npm install @extjs/sencha-cmd` but still the same error 😞

**Comment by israelroldan** [comment] 2017-05-17 17:20
@abenhamdine what happens if you try to run `bin/sencha.cmd` from there? you could try that or `node bin/sencha`

**Comment by abenhamdine** [comment] 2017-05-17 17:26
seems to work :  
```bash
Arnaud Benhamdine@LAPTOP-ARNAUD MINGW64 /c/node-projects/extjs-reactor/packages/reactor-modern-boilerplate/node_modules/@extjs/sencha-cmd
$ bin/sencha
Sencha Cmd v6.5.0.180
Sencha Cmd provides several categories of commands and some global switches. In

**Comment by markbrocato** [comment] 2017-05-18 14:27
We have published a fix for the "Cannot satisfy requirements for "modern"" error on Windows as a prerelease of v1.0.1.  You can give it a try by running the following in reactor-classic-boilerplate or reactor-modern-boilerplate:

```
npm install @extjs/reactor-webpack-plugin@next
```

**Comment by dkelly99** [comment] 2017-05-18 16:44
**I'm pretty sure this is somehow related to sencha-cmd.**

I had a similar issue on ```reactor-boilerplate```.  I keep getting the following error when I try to run ```npm start```
`````
.....
10% building modules 1/1 modules 0 active
Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from ./build
404s will fallback to /index.html
 94% asset optimization
building ExtReact bundle: ext => C:\sandbox\extjs-reactor\packages\reactor-boilerplate\build\ext-react
undefined
(node:5256) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of undefined

`````
Note that the node:ref# above is different each time I run ```npm start```.

When I navigated to ```C:\sandbox\extjs-reactor\packages\reactor-boilerplate\node_modules\@extjs\sencha-cmd``` folder and run ```node bin/sencha``` I got the following error...

`````
[ERR] Error: spawn C:\sandbox\extjs-reactor\packages\reactor-boilerplate\node_modules\@extjs\sencha-cmd\node_modules\@extjs\sencha-cmd-windows-64-jre\dist\sencha.exe ENOENT
......
`````
HOWEVER, when I navigate to THAT location, ```sencha.exe``` does NOT exist.  The actual file at that location is named ```SenchaCmd-6.5.0.180-windows-64bit.exe```.  

When I renamed this to ```sencha.exe``` and tried ```npm start``` again, it does get a bit further - the sencha-cmd install process kicks in and appears successful, but it still eventually fails with the same error. 
```(node:9404) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of undefined```.

Now, each time I run ```npm start``` from within the ```reactor-boilerplate``` folder, the install wizard for sencha-cmd kicks in every time - each time it appears that sencha-cmd is installed successfully but each time the ```npm start``` will eventually fail with the same ```UnhandledPromiseRejectionWarning```.

I don't know if I am correct to rename the above file but I hope this helps to narrow down the issue.

BTW, my environment:
  Windows 10 Home
  node: 6.9.4
  npm: 4.6.1

**Comment by jsheely** [comment] 2017-05-18 18:14
I'm in the same boat as @dkelly99 on windows. 

@markbrocato ```npm install @extjs/reactor-webpack-plugin@next``` does not work. I tried @latest and get the same result

**Comment by israelroldan** [comment] 2017-05-18 18:55
@dkelly99 @jsheely that definitely sounds like an install-time issue with `@extjs/sencha-cmd` with a bundled JRE, we'll have a fix for that soon. In the meantime, if you're able to install a Java 7+ JRE (and make sure it is in your PATH) it may help (since `@extjs/sencha-cmd` will get the unpacked bits, as opposed to the installer version).

@jsheely `@next` should be available in the private registry just now, could you please try again? (just to confirm you have access to it, not the fix itself)

**Comment by jsheely** [comment] 2017-05-18 19:15
@israelroldan Yes it is there now.

**Comment by jsheely** [comment] 2017-05-18 19:18
@israelroldan @dkelly99  Installing the Java runtime manually and re-doing npm-install solved the problem.

Thank you sir

**Comment by dkelly99** [comment] 2017-05-18 20:09
@israelroldan @jsheely Thanks so much.  I upgraded Java to latest version (8), deleted `node_modules` reactor-boilerplate/folder` (just to make sure I had a clean install) and then ran `npm install` followed by `npm start`.  Everything worked perfectly this time.  Thanks again.

**Comment by markbrocato** [comment] 2017-05-19 13:27
Closing this as it seems everyone's issues have been worked out.  We plan to release reactor-webpack-plugin v1.0.1 next week which will contain the windows fix.

**Closed by markbrocato** 2017-05-19 13:27 UTC

**Comment by abenhamdine** [comment] 2017-05-19 14:11
Personnaly, I still have the problem.

I reinstalled JRE 8 and put it in the path, and still encounter : 
```
Arnaud Benhamdine@LAPTOP-ARNAUD MINGW64 /c/node-projects/extjs-reactor/packages/reactor-modern-boilerplate
$ npm start

> @extjs/react-modern-boilerplate@1.0.0 start C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate
> webpack-dev-server --progress --colors

 10% building modules 1/1 modules 0 active
Project is running at http://localhost:8086/
webpack output is served from /
Content not from webpack is served from ./build
404s will fallback to /index.html                                                                                      94% asset optimization                   building ExtReact bundle: ext => C:\node-projects\extjs-reactor\packages\reactor-modern-boilerplate\build\ext-react
Sencha Cmd v6.5.0.180
[INF] Loading compiler context
[ERR] Cannot satisfy requirements for "modern"!
[ERR]    The following versions cannot be satisfied:
[ERR]       null: modern (No matches!)
[ERR]
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExVersion: Cannot resolve package requirements
[ERR]
[ERR] Total time: 7 seconds
[ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExVersion: Cannot resolve package requirements
undefined
(node:1104) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of undefined
(node:1104) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I can wait for the next week fix, that said.

**Comment by markbrocato** [comment] 2017-05-19 14:12
@abenhamdine That should be fixed by installing the prerelease of reactor-webpack plugin 1.0.1:

```
npm install --save-dev @extjs/reactor-webpack-plugin@next
```
